-- SEQUENCE
--게시판용 테이블 생성
CREATE TABLE BOARD (
	NO NUMBER,
	TITLE VARCHAR(4000),
	CONTENT CLOB,
	WRITER VARCHAR(1000),
	REGDATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE SEQ_BOARD;

INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER) VALUES (SEQ_BOARD.NEXTVAL, '제목', '내용', '새똥이');

SELECT * FROM BOARD;

COMMIT;

INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER)
SELECT SEQ_BOARD.NEXTVAL NO, TITLE, CONTENT, WRITER FROM BOARD;