-- 요일 셋팅
SELECT MAX(SUN), MAX(MON), MAX(TUE), MAX(WED) ,MAX(THUR),MAX(FRI), MAX(SAT) FROM ( 
	SELECT 1 SUN, NULL MON, NULL TUE, NULL WED, NULL THUR, NULL FRI, NULL SAT FROM DUAL
	UNION
	SELECT NULL, 2, NULL, NULL, NULL, NULL, NULL FROM DUAL
	UNION
	SELECT NULL, NULL, 3, NULL, NULL, NULL, NULL FROM DUAL
	UNION
	SELECT NULL, NULL, NULL, 4, NULL, NULL, NULL FROM DUAL
	UNION
	SELECT NULL, NULL, NULL, NULL, 5, NULL, NULL FROM DUAL
	UNION
	SELECT NULL, NULL, NULL, NULL, NULL, 6, NULL FROM DUAL
	UNION
	SELECT NULL, NULL, NULL, NULL, NULL, NULL, 7 FROM DUAL
	);
	
-- 날짜 셋팅
SELECT 
	MAX(DECODE(MOD(RN, 7), 1, RN)) SUN, 
	MAX(DECODE(MOD(RN, 7), 2, RN)) MON,
	MAX(DECODE(MOD(RN, 7), 3, RN)) TUE,
	MAX(DECODE(MOD(RN, 7), 4, RN)) WED,
	MAX(DECODE(MOD(RN, 7), 5, RN)) THUR,
	MAX(DECODE(MOD(RN, 7), 6, RN)) FRI,
	MAX(DECODE(MOD(RN, 7), 0, RN)) SAT
FROM(
	SELECT 
		ROWNUM RN ,
		TO_CHAR(TO_DATE('2024-09-' || LTRIM(TO_CHAR(ROWNUM, '00'))), 'W') WEEK
	FROM DICT 
	WHERE ROWNUM <= TO_CHAR(LAST_DAY(TO_DATE('2024-09', 'YYYY-MM')), 'DD')
) 
GROUP BY WEEK
ORDER BY WEEK;
