-- 사번, 이름, 부서 번호, 부서 이름 조회
SELECT 	e.EMPLOYEE_ID , e.LAST_NAME , e.DEPARTMENT_ID, d.DEPARTMENT_NAME 
FROM EMPLOYEES e , DEPARTMENTS d 
WHERE e.DEPARTMENT_ID  = d.DEPARTMENT_ID ;

SELECT COUNT(*)
FROM EMPLOYEES e ;

-- 사번, 성, 상사의 사번, 상사의 성
SELECT e.EMPLOYEE_ID, e.LAST_NAME, e2.EMPLOYEE_ID , e2.LAST_NAME 
FROM EMPLOYEES e 
LEFT JOIN EMPLOYEES e2 ON e.MANAGER_ID = e2.EMPLOYEE_ID 
ORDER BY 1;